name: Dev Pipeline With Approval

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Step (Dev)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build step
        run: echo "Building application in DEV environment..."

      - name: Run tests
        run: echo "Running tests in DEV..."
  

  deploy-dev:
    name: Deploy to Dev (Requires Approval)
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy step
        run: echo "Deploying to DEV after approval..."
